/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nibiru API
 * Nibiru API Documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSandboxRequest,
  ListResult,
  LoginRequest,
  RegisterRequest,
  SandboxListParams,
  SandboxSummary,
  User
} from './model';

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type authRegisterResponse204 = {
  data: void
  status: 204
}

export type authRegisterResponseSuccess = (authRegisterResponse204) & {
  headers: Headers;
};
;

export type authRegisterResponse = (authRegisterResponseSuccess)

export const getAuthRegisterUrl = () => {




  return `/auth/register`
}

export const authRegister = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<authRegisterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authRegisterResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as authRegisterResponse
}





export const getAuthRegisterMutationKey = () => ['authRegister'] as const;

export const getAuthRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,AuthRegisterMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,AuthRegisterMutationVariables, TContext> => {

const mutationKey = getAuthRegisterMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRegister>>, AuthRegisterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authRegister(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authRegister>>>
    export type AuthRegisterMutationBody = RegisterRequest
    export type AuthRegisterMutationError = unknown
    export type AuthRegisterMutationVariables = {data: RegisterRequest}

    export const useAuthRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,AuthRegisterMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authRegister>>,
        TError,
        AuthRegisterMutationVariables,
        TContext
      > => {
      return useMutation(getAuthRegisterMutationOptions(options), queryClient);
    }

export type authLoginResponse200 = {
  data: User
  status: 200
}

export type authLoginResponseSuccess = (authLoginResponse200) & {
  headers: Headers;
};
;

export type authLoginResponse = (authLoginResponseSuccess)

export const getAuthLoginUrl = () => {




  return `/auth/login`
}

export const authLogin = async (loginRequest: LoginRequest, options?: RequestInit): Promise<authLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authLoginResponse
}





export const getAuthLoginMutationKey = () => ['authLogin'] as const;

export const getAuthLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,AuthLoginMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,AuthLoginMutationVariables, TContext> => {

const mutationKey = getAuthLoginMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogin>>, AuthLoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authLogin(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
    export type AuthLoginMutationBody = LoginRequest
    export type AuthLoginMutationError = unknown
    export type AuthLoginMutationVariables = {data: LoginRequest}

    export const useAuthLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,AuthLoginMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogin>>,
        TError,
        AuthLoginMutationVariables,
        TContext
      > => {
      return useMutation(getAuthLoginMutationOptions(options), queryClient);
    }

export type authMeResponse200 = {
  data: User
  status: 200
}

export type authMeResponseSuccess = (authMeResponse200) & {
  headers: Headers;
};
;

export type authMeResponse = (authMeResponseSuccess)

export const getAuthMeUrl = () => {




  return `/auth/me`
}

export const authMe = async ( options?: RequestInit): Promise<authMeResponse> => {

  const res = await fetch(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authMeResponse
}





export const getAuthMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }


export const getAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMe>>> = ({ signal }) => authMe({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>
export type AuthMeQueryError = unknown


export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type authLogoutResponse204 = {
  data: void
  status: 204
}

export type authLogoutResponseSuccess = (authLogoutResponse204) & {
  headers: Headers;
};
;

export type authLogoutResponse = (authLogoutResponseSuccess)

export const getAuthLogoutUrl = () => {




  return `/auth/logout`
}

export const authLogout = async ( options?: RequestInit): Promise<authLogoutResponse> => {

  const res = await fetch(getAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authLogoutResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as authLogoutResponse
}





export const getAuthLogoutMutationKey = () => ['authLogout'] as const;

export const getAuthLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext> => {

const mutationKey = getAuthLogoutMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {


          return  authLogout(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>

    export type AuthLogoutMutationError = unknown


    export const useAuthLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthLogoutMutationOptions(options), queryClient);
    }

export type sandboxListResponse200 = {
  data: ListResult
  status: 200
}

export type sandboxListResponseSuccess = (sandboxListResponse200) & {
  headers: Headers;
};
;

export type sandboxListResponse = (sandboxListResponseSuccess)

export const getSandboxListUrl = (params?: SandboxListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/sandbox?${stringifiedParams}` : `/sandbox`
}

/**
 * Lists the authenticated user's sandboxes, newest first, using cursor pagination.
 * @summary List sandboxes
 */
export const sandboxList = async (params?: SandboxListParams, options?: RequestInit): Promise<sandboxListResponse> => {

  const res = await fetch(getSandboxListUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: sandboxListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sandboxListResponse
}





export const getSandboxListQueryKey = (params?: SandboxListParams,) => {
    return [
    `/sandbox`, ...(params ? [params] : [])
    ] as const;
    }


export const getSandboxListQueryOptions = <TData = Awaited<ReturnType<typeof sandboxList>>, TError = unknown>(params?: SandboxListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sandboxList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSandboxListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sandboxList>>> = ({ signal }) => sandboxList(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sandboxList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SandboxListQueryResult = NonNullable<Awaited<ReturnType<typeof sandboxList>>>
export type SandboxListQueryError = unknown


export function useSandboxList<TData = Awaited<ReturnType<typeof sandboxList>>, TError = unknown>(
 params: undefined |  SandboxListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sandboxList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sandboxList>>,
          TError,
          Awaited<ReturnType<typeof sandboxList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSandboxList<TData = Awaited<ReturnType<typeof sandboxList>>, TError = unknown>(
 params?: SandboxListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sandboxList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sandboxList>>,
          TError,
          Awaited<ReturnType<typeof sandboxList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSandboxList<TData = Awaited<ReturnType<typeof sandboxList>>, TError = unknown>(
 params?: SandboxListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sandboxList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List sandboxes
 */

export function useSandboxList<TData = Awaited<ReturnType<typeof sandboxList>>, TError = unknown>(
 params?: SandboxListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sandboxList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSandboxListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type sandboxCreateResponse201 = {
  data: SandboxSummary
  status: 201
}

export type sandboxCreateResponseSuccess = (sandboxCreateResponse201) & {
  headers: Headers;
};
;

export type sandboxCreateResponse = (sandboxCreateResponseSuccess)

export const getSandboxCreateUrl = () => {




  return `/sandbox`
}

/**
 * @summary Create a sandbox
 */
export const sandboxCreate = async (createSandboxRequest: CreateSandboxRequest, options?: RequestInit): Promise<sandboxCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getSandboxCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createSandboxRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: sandboxCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sandboxCreateResponse
}





export const getSandboxCreateMutationKey = () => ['sandboxCreate'] as const;

export const getSandboxCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sandboxCreate>>, TError,SandboxCreateMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof sandboxCreate>>, TError,SandboxCreateMutationVariables, TContext> => {

const mutationKey = getSandboxCreateMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sandboxCreate>>, SandboxCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  sandboxCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SandboxCreateMutationResult = NonNullable<Awaited<ReturnType<typeof sandboxCreate>>>
    export type SandboxCreateMutationBody = CreateSandboxRequest
    export type SandboxCreateMutationError = unknown
    export type SandboxCreateMutationVariables = {data: CreateSandboxRequest}

    /**
 * @summary Create a sandbox
 */
export const useSandboxCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sandboxCreate>>, TError,SandboxCreateMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sandboxCreate>>,
        TError,
        SandboxCreateMutationVariables,
        TContext
      > => {
      return useMutation(getSandboxCreateMutationOptions(options), queryClient);
    }
