/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nibiru API
 * Nibiru API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  LoginRequest,
  RegisterRequest,
  User
} from '../model';


export type authRegisterResponse204 = {
  data: void
  status: 204
}

export type authRegisterResponseSuccess = (authRegisterResponse204) & {
  headers: Headers;
};
;

export type authRegisterResponse = (authRegisterResponseSuccess)

export const getAuthRegisterUrl = () => {




  return `http://localhost:7000/auth/register`
}

export const authRegister = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<authRegisterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authRegisterResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as authRegisterResponse
}


export type authLoginResponse200 = {
  data: User
  status: 200
}

export type authLoginResponseSuccess = (authLoginResponse200) & {
  headers: Headers;
};
;

export type authLoginResponse = (authLoginResponseSuccess)

export const getAuthLoginUrl = () => {




  return `http://localhost:7000/auth/login`
}

export const authLogin = async (loginRequest: LoginRequest, options?: RequestInit): Promise<authLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authLoginResponse
}


export type authMeResponse200 = {
  data: User
  status: 200
}

export type authMeResponseSuccess = (authMeResponse200) & {
  headers: Headers;
};
;

export type authMeResponse = (authMeResponseSuccess)

export const getAuthMeUrl = () => {




  return `http://localhost:7000/auth/me`
}

export const authMe = async ( options?: RequestInit): Promise<authMeResponse> => {

  const res = await fetch(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authMeResponse
}


export type authLogoutResponse204 = {
  data: void
  status: 204
}

export type authLogoutResponseSuccess = (authLogoutResponse204) & {
  headers: Headers;
};
;

export type authLogoutResponse = (authLogoutResponseSuccess)

export const getAuthLogoutUrl = () => {




  return `http://localhost:7000/auth/logout`
}

export const authLogout = async ( options?: RequestInit): Promise<authLogoutResponse> => {

  const res = await fetch(getAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authLogoutResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as authLogoutResponse
}


