/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nibiru API
 * Nibiru API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateSandboxRequest,
  ListResult,
  SandboxListParams,
  SandboxSummary
} from '../model';


export type sandboxListResponse200 = {
  data: ListResult
  status: 200
}

export type sandboxListResponseSuccess = (sandboxListResponse200) & {
  headers: Headers;
};
;

export type sandboxListResponse = (sandboxListResponseSuccess)

export const getSandboxListUrl = (params?: SandboxListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:7000/sandbox?${stringifiedParams}` : `http://localhost:7000/sandbox`
}

/**
 * Lists the authenticated user's sandboxes, newest first, using cursor pagination.
 * @summary List sandboxes
 */
export const sandboxList = async (params?: SandboxListParams, options?: RequestInit): Promise<sandboxListResponse> => {

  const res = await fetch(getSandboxListUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: sandboxListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sandboxListResponse
}


export type sandboxCreateResponse201 = {
  data: SandboxSummary
  status: 201
}

export type sandboxCreateResponseSuccess = (sandboxCreateResponse201) & {
  headers: Headers;
};
;

export type sandboxCreateResponse = (sandboxCreateResponseSuccess)

export const getSandboxCreateUrl = () => {




  return `http://localhost:7000/sandbox`
}

/**
 * @summary Create a sandbox
 */
export const sandboxCreate = async (createSandboxRequest: CreateSandboxRequest, options?: RequestInit): Promise<sandboxCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getSandboxCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createSandboxRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: sandboxCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sandboxCreateResponse
}


