/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nibiru API
 * Nibiru API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSandboxRequest {
  cpu: number;
  disk: number;
  name?: string;
  ram: number;
}
