/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nibiru API
 * Nibiru API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SandboxSummary } from './sandboxSummary';

export interface ListResult {
  items: SandboxSummary[];
  /** @nullable */
  nextCursor: string | null;
}
