/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nibiru API
 * Nibiru API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  email: string;
  firstName: string;
  /** @nullable */
  lastName?: string | null;
  password: string;
}
