/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nibiru API
 * Nibiru API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SandboxSummaryState } from './sandboxSummaryState';

export interface SandboxSummary {
  cpu: number;
  disk: number;
  id: string;
  name: string;
  ram: number;
  state: SandboxSummaryState;
}
